name: siimple
description: Simple but powerful NoSQL database for flutter.
version: 0.0.4
repository: https://github.com/hir4k/siimple.git
issue_tracker: https://github.com/hir4k/siimple/issues
topics:
  - database
  - siimple
  - sqlite
  - isar
  - storage

environment:
  sdk: ^3.5.4

dependencies:
  path_provider: ^2.1.5
  uuid: ^4.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
